### ISSUE TITLE
Refactorisation de l'architecture CLI - Unification des points d'entrée dans src/cli/

### ISSUE THREAD

**Issue by BittnerPierre** [BittnerPierre/AI-Agent-Casebook#111]
## 🎯 Objectif

Refactoriser l'architecture des CLI pour améliorer la cohérence et la maintenabilité du projet.

## 📊 Situation actuelle

Les deux CLI du projet ont des structures incohérentes :

```toml
[tool.poetry.scripts]
run_training_manager = "src.training_manager.main:cli_main"          # ❌ Dans le package métier
transcript-generator = "cli.transcript_generator_cli:main"           # ❌ Répertoire CLI isolé
```

## 🎯 Architecture cible

Créer un package unifié `src/cli/` pour tous les points d'entrée :

```
src/
├── cli/
│   ├── __init__.py
│   ├── training_manager_cli.py      # Déplacé depuis src/training_manager/main.py
│   └── transcript_generator_cli.py  # Déplacé depuis cli/transcript_generator_cli.py
├── training_manager/
│   ├── core.py                      # Logic métier uniquement
│   ├── agents/
│   └── tools/
└── transcript_generator/
    ├── workflow_orchestrator.py     # Logic métier uniquement
    ├── agents/
    └── tools/
```

### 1. Structure des fichiers

- [ ] Créer `src/cli/__init__.py`
- [ ] Déplacer `src/training_manager/main.py` → `src/cli/training_manager_cli.py`
- [ ] Déplacer `cli/transcript_generator_cli.py` → `src/cli/transcript_generator_cli.py`
- [ ] Supprimer le répertoire `cli/` à la racine

### 2. Configuration Poetry

```toml
[tool.poetry.scripts]
run_training_manager = "src.cli.training_manager_cli:cli_main"
transcript-generator = "src.cli.transcript_generator_cli:main"
```

### 3. Ajustements d'imports

- [ ] Corriger les imports relatifs dans les CLI déplacés
- [ ] Mettre à jour les références dans les tests
- [ ] Vérifier les scripts shell (`run_training_manager.sh`)

### 4. Tests et validation

- [ ] Mettre à jour les chemins dans les tests
- [ ] Valider que `poetry run run_training_manager` fonctionne
- [ ] Valider que `poetry run transcript-generator` fonctionne
- [ ] Vérifier les scripts d'intégration

## 💡 Bénéfices

✅ **Cohérence** : Structure unifiée pour tous les CLI
✅ **Séparation des responsabilités** : UI distincte de la logique métier
✅ **Maintenabilité** : Facilite l'ajout de nouveaux CLI
✅ **Standards** : Suit les conventions Python pour les projets complexes
✅ **Évolutivité** : Prépare l'ajout d'autres outils CLI

## 📋 Acceptance Criteria

- [ ] Tous les CLI sont dans `src/cli/`
- [ ] Les scripts Poetry fonctionnent sans changement pour l'utilisateur
- [ ] Tous les tests passent
- [ ] La documentation est mise à jour
- [ ] Le répertoire `cli/` racine est supprimé
